# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 04:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_type', models.CharField(max_length=200)),
                ('dish_category', models.CharField(max_length=50)),
                ('dish_name', models.CharField(max_length=100)),
                ('dish_description', models.TextField()),
                ('dish_price', models.IntegerField()),
            ],
        ),
    ]
